# Creates workflow
name: NASA Project CI
on:
  push:
    branches: [master] # workflow will be defined on a push request
  pull_request:
    branches: [master] # workflow will be defined on a pull request
jobs: # define jobs that will run, will run in parallel. Can specify dependency with 'needs'
  build:
    runs-on: ubuntu-latest # what our server runs on -> best supported
    steps: # actions that will be taken on request
      - uses: actions/checkout@v2 # build in to github actions, specify version of checkout action
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: "16" # uses node version 16
      - run: npm install # runs terminal commands
      - run: npm run build --prefix client # want to run our build on the front-end code, runs build in create-react app
