# Creates workflow
name: NASA Project CI
on:
  push:
    branches: [main] # workflow will be defined on a push request
  pull_request:
    branches: [main] # workflow will be defined on a pull request
jobs: # define jobs that will run, will run in parallel. Can specify dependency with 'needs'
  build:
    env:
      CI: true # Disables watch mode
    strategy:
      matrix:
        node-version: [14.x, 16.x] # runs different versions of node
    runs-on: ubuntu-latest # what our server runs on -> best supported
    steps: # actions that will be taken on request
      - uses: actions/checkout@v2 # build in to github actions, specify version of checkout action
      - name: Use Node.js version ${{ matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version}} # uses node version 16
      - run: npm install # runs terminal commands
      - run: npm run build --prefix client # want to run our build on the front-end code, runs build in create-react app
      # - run: npm test
